config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { registrations: 'registrations' }
  root 'pages#index'
  
  get 'pages/index'

  get 'pages/about'

  get 'pages/contact'
  

  
  

end

app/models/article.rb
class Article < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
    before_action :set_article, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /articles
  # GET /articles.json
  def index
    @articles = Article.paginate(page: params[:page], per_page: 2) 
    @last5 = Article.last(5)
  end

  # GET /articles/1
  # GET /articles/1.json
  def show
  end

  # GET /articles/new
  def new
    @article = current_user.articles.build
  end

  # GET /articles/1/edit
  def edit
  end

  # POST /articles
  # POST /articles.json
  def create
    @article = current_user.articles.build(article_params)

    respond_to do |format|
      if @article.save
        format.html { redirect_to @article, notice: 'Article was successfully created.' }
        format.json { render :show, status: :created, location: @article }
      else
        format.html { render :new }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /articles/1
  # PATCH/PUT /articles/1.json
  def update
    respond_to do |format|
      if @article.update(article_params)
        format.html { redirect_to @article, notice: 'Article was successfully updated.' }
        format.json { render :show, status: :ok, location: @article }
      else
        format.html { render :edit }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1
  # DELETE /articles/1.json
  def destroy
    @article.destroy
    respond_to do |format|
      format.html { redirect_to articles_url, notice: 'Article was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_article
      @article = Article.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def article_params
      params.require(:article).permit(:title, :body)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
    
  
  def index
    if current_user
      redirect_to articles_index_path
    end
    @articles = Article.last(5)
  end

  def contact
    @contact = Contact.new  
  end

  def about
  
  end
  
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

  private

  def sign_up_params
    params.require(:user).permit(
      :email, 
      :password, 
      :password_confirmation,
      :username,
      :firstname,
      :lastname
      )
  end

  def account_update_params
    params.require(:user).permit(
      :email, 
      :password, 
      :password_confirmation, 
      :current_password,
      :username,
      :firstname,
      :lastname
      )
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/articles/index.html.erb
<h1>Articles#index</h1>
<p>Find me in app/views/articles/index.html.erb</p>

app/views/layouts/_foot.html.erb
<% if current_user %>

<link href="//maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css" rel="stylesheet">

<footer class="text-muted well" id="last-footer">
	<section>
		<div class="row" style="font-size:11px;">
		<div class="container">
		<h3 class="subhead" style="text-align:center;">All We Need Is Your Love</h3>
		   <div class="col-md-9">
        <div class="row" >
			<div class="col-md-3">
			<div class="row footlinks">
			<div class="col-xs-12">
			<h5>About School</h5>
			<ul class="noBullets">
			<li><i class="fa fa-angle-right"></i><a href="#">History</a></li>
			<li><i class="fa fa-angle-right"></i><a href="#">Location</a></li>
			<li><i class="fa fa-angle-right"></i><a href="#">Faculty</a></li>
			<li><i class="fa fa-angle-right"></i><a href="#">Architecture</a></li>
			</ul>
			</div>
			</div>
			</div>
			<div class="col-md-3">
			<div class="row footlinks">
			<div class="col-xs-12">
			<h5>Join Us</h5>
			<ul class="noBullets">
			<li><i class="fa fa-angle-right"></i><a href="#">Facbook Page</a></li>
			<li><i class="fa fa-angle-right"></i><a href="#">Follow Twitter</a></li>
			<li><i class="fa fa-angle-right"></i><a href="#">Google Plus</a></li>
			<li><i class="fa fa-angle-right"></i><a href="#">E-Mail</a></li>
			</ul>
			</div>
			</div>
			</div>
			<div class="col-md-3">
			<div class="row footlinks">
			<div class="col-xs-12">
			<h5>Facilities</h5>
			<ul class="noBullets">
			<li><i class="fa fa-angle-right"></i><a href="#">Transport Facility</a></li>
			<li><i class="fa fa-angle-right"></i><a href="#">AC Classrooms</a></li>
			<li><i class="fa fa-angle-right"></i><a href="#">Monthly Trips</a></li>
			<li><i class="fa fa-angle-right"></i><a href="#">Computer Lab</a></li>
			</ul>
			</div>
			</div>
			</div>
			<div class="col-md-3">
			<div class="row footlinks">
			<div class="col-xs-12">
			<h5>Access Links</h5>
			<ul class="noBullets">
			<li><i class="fa fa-angle-right"></i><a href="#">Future Plans</a></li>
			<li><i class="fa fa-angle-right"></i><a href="#">Objectives</a></li>
			<li><i class="fa fa-angle-right"></i><a href="#">Achievements</a></li>
			<li><i class="fa fa-angle-right"></i><a href="#">Honours</a></li>
			</ul>
			</div>
			</div>
			</div>
			<hr/>			
        </div><!--/.row inner--> 
		</div>
		 <div class="col-md-3 subscribe">
		 <div class="row">
		 <div class="col-xs-12">
		 <form class="form-inline" role="form">
		 <ul class="noBullets">
		<h5>Subscribe Newsletters!</h5>
		 <li>
		 <div class="form-group">
				    <input type="email" class="form-control" id="exampleInputEmail1" placeholder="Enter your email address">
		</div>
				  </li>
				  <li class="text-center">
				  <button type="submit" class="btn btn-success btn-sm">Subscribe Now!</button>
				  </li>
				  </ul>		
				</form>		
		</div></div>		
		 </div>
		
    
		<footer>	<div class="row">
			<div class="container text-center">
				<h5>All Rights Reserved © 2014.<a href="mailto:chance2seo@gmail.com">Passionate Rahul</a></h5>
			</div>
			        </div>
			
	    </footer>
			 </div><!--/.container--> 
			 </div><!--/.row outer--> 
	</section>
</footer>

<% else %>

<footer class="footer-distributed">

	<div class="footer-left">
	    
	    <h3>Company<span>Logo</span></h3>
	    
	        <p class="footer-links">
                <a href="#">Home</a>
                ·
                <a href="#">Blog</a>
                ·
                <a href="#">Pricing</a>
                ·
                <a href="#">About</a>
                ·
                <a href="#">Faq</a>
                ·
                <a href="#">Contact</a>
            </p>
            
        <p class="footer-company-name">Company Name &copy; 2017</p>        
            
	<div class="footer-icons">

		<a href="#"><i class="fa fa-facebook"></i></a>
		<a href="#"><i class="fa fa-twitter"></i></a>
		<a href="#"><i class="fa fa-linkedin"></i></a>
		<a href="#"><i class="fa fa-github"></i></a>

	</div>
		
	<div class="footer-right">
	    
	    
	    <form action="#" method="post">
            <input type="text" name="email" placeholder="Email" />
            <textarea name="message" placeholder="Message"></textarea>
            <button>Send</button>
        </form>

	</div>

</footer>



<% end %>

app/views/layouts/_nav.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Nicky's Articles", root_path, class: 'navbar-brand' %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      
      
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to 'Contact Us', pages_contact_path %></li>
        <li><%= link_to 'About Us', pages_about_path %></li>
        <li><%= link_to 'Sign Up', new_user_registration_path %></li>
        <li><%= link_to 'Sign In', new_user_session_path %></li>
        <li><%= link_to 'Sign Out', destroy_user_session_path, method: :delete %></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="#">Action</a></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">Separated link</a></li>
          </ul>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Workspace</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>

  <body>
  
    <%= bootstrap_flash %>
  
    <%= render 'layouts/nav' %>
  
    <div class='container'>
        <%= yield %>
    </div>
  
    <%= render 'layouts/foot' %>
    
  </body>

</html>

app/views/pages/about.html.erb
<div class="row">
    <div class="col-lg-12 text-center">
        <h1>About Us</h1>
        <p class="lead">Test Text</p>
        <ul class="list-unstyled">
            <li>List Item</li>
            <li>List Item 2</li>
        </ul>
    </div>
</div>

app/views/pages/contact.html.erb
<div class="row">
    <div class="col-lg-12 text-center">
        <h1>Contact Us</h1>
        <p class="lead">Test Text</p>
        <ul class="list-unstyled">
            <li>List Item</li>
            <li>List Item 2</li>
        </ul>
    </div>
</div>

app/views/pages/index.html.erb
<h1>Welcome Nicky!</h1>
<p>Today is a great day to get better at MadFrog!</p>

<div>
<p>Nicky Brams ToDoList</p>
    <li>
        <ul> Item 1</ul>
        <ul> Item 2</ul>
        <ul> Item 3</ul>
        <ul> Item 4</ul>
        <ul> Item 5</ul>
    </li>
</div>